### ISSUE TITLE
Feature request: "Folders" functionality

### ISSUE THREAD

**Issue by NavaneethakrishnanVG** [hwgilbert16/scholarsome#104]
_**Hello devs!**_
As a user of Scholarsome, I'm impressed with the overall UX and excited about its potential. While I find most features intuitive, I believe adding "**folder**" functionality would significantly improve organization and usability.
Currently, all files appear on a single page, regardless of topic. This can become overwhelming as I create data sets for various subjects like math, science, and English. Implementing folders would allow me to:
- **Group files by topic:** Organize my resources logically, making them easier to find and access.
- **Improve clarity and visual hierarchy:** Reduce clutter and enhance the user experience for managing numerous files.
- **Enable future UI/UX enhancements:** Lay the groundwork for further organizational features like subfolders or tags.

I understand that UI/UX refinements can follow after the core functionality is established. My primary request is for the basic folder feature to be implemented, allowing for initial organization.
I believe this feature would benefit numerous users by streamlining resource management.

**Comment by hwgilbert16** [comment]
That's a great idea. This was something planned earlier on, but I hadn't gotten around to implementing it.

Will be in either next release or the one after.

**Comment by hwgilbert16** [comment]
This feature is complete and will be publicly available upon the release of v1.0.2
