### ISSUE TITLE
Handle special characters in title/description

### ISSUE THREAD

**Issue by astevens20** [hwgilbert16/scholarsome#109]
_Edited to include a better example_

Special characters are allowed to be inputted into the title and description for a new set:
![image](https://github.com/hwgilbert16/scholarsome/assets/158517674/7dbd9776-2353-455b-a1d1-82356b16fb84)

However, not all of them are rendered correctly upon saving the set:
![image](https://github.com/hwgilbert16/scholarsome/assets/158517674/865923ae-fc3a-40b2-ac28-20040e5ea181)

In my example, this is the string that I used for the title:
```! @ # $ % ^ & * ( ) _ + - = [ ] \ { } | ? / ~ ` < > , . ä ö```

And here is the resulting title:
```! @ # $ % ^ &amp; * ( ) _ + - = [ ] \ { } | ? / ~ ` &lt; &gt; , . ä ö```

The characters that did not render are:
```
&
<
>
```

**Comment by hwgilbert16** [comment]
Good catch. This has been fixed in 52a854ee90febc309f87a919e69dbe02bd41b7be by implementing a pipe on the API side to automatically translate these three characters back to their original rendering.

The fix will be available in the next release.
