### ISSUE TITLE
Always jump user to their newly-created set after .csv upload

### ISSUE THREAD

**Issue by astevens20** [hwgilbert16/scholarsome#110]
This is relatively minor but would be nice for usability's sake.

When creating a new set by CSV upload, whether you are automatically brought to the newly-created set is inconsistent based on what activity you have open.

**Workflow 1:**
1. Have an already-created set opened
2. Create a new set via CSV upload
3. Outcome: you **are not** automatically navigated to your newly-created set
![Scholarsome_issue110_workflow1](https://github.com/hwgilbert16/scholarsome/assets/158517674/d27a6829-789f-4613-98a2-103c61a0aebb)

**Workflow 2:**
1. Start on your "my sets" page
2. Create a new set via CSV upload
3. Outcome: you **are** automatically navigated to your newly-created set

![Scholarsome_issue110_workflow2](https://github.com/hwgilbert16/scholarsome/assets/158517674/7243690e-548b-4e5c-b056-157b251ee24d)

Also - thanks for your patience with all of my issues! I realize these are minor but I feel better making sure they're documented! :)

**Comment by hwgilbert16** [comment]
I noticed this issue before, but wasn't able to find out how to always reproduce it. Thank you for the report - it's always good to document them :). This has been fixed in 52a854ee90febc309f87a919e69dbe02bd41b7be

The fix will be available in the next release.
