### ISSUE TITLE
Enforce semantic commit messages

### ISSUE THREAD

**Issue by hwgilbert16** [hwgilbert16/scholarsome#118]
Using Husky and commitlint, commit messages should be enforced using a semantic style:

`<type>(<scope>): <subject>, not this: (<scope>) <type>: <subject>`

**Comment by Jayanth-Parthsarathy** [comment]
Hey there @hwgilbert16. I would love to work on this can I get this assigned please?

**Comment by hwgilbert16** [comment]
> Hey there @hwgilbert16. I would love to work on this can I get this assigned please?

Yes - I've assigned you this issue.

**Comment by Jayanth-Parthsarathy** [comment]
@hwgilbert16. To be more clear the commit should be of the format `(api + docs) feat: add correct response bodies for folder endpoints` right as seen from the previous commits. Please correct me if I am wrong.

**Comment by WhyNeet** [comment]
Hey @Jayanth-Parthsarathy. The commit message format is described in [Angular repository](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit). Commitlint has a prebuilt config for conventional commit messages: `@commitlint/config-conventional`

**Comment by Jayanth-Parthsarathy** [comment]
> Hey @Jayanth-Parthsarathy. The commit message format is described in [Angular repository](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit). Commitlint has a prebuilt config for conventional commit messages: `@commitlint/config-conventional`

Thank you for your input! I thought I had to add some custom rule to parse the commit message in addition to `@commitlint/config-conventional`. Thanks for the heads up 👍🏽

**Comment by Jayanth-Parthsarathy** [comment]
Hey @hwgilbert16. Please have a look and let me know if any changes are to be made.
