### ISSUE TITLE
Import sets from Anki

### ISSUE THREAD

**Issue by hwgilbert16** [hwgilbert16/scholarsome#12]
Many users have large sets already at Anki. There should be the ability to import these sets without manual copy and pasting, just like the Quizlet import functionality.

**Comment by diomed** [comment]
hey

maybe also import from json file?

like there are some json files that have periodic system of elements and such

**Comment by hwgilbert16** [comment]
> hey
> 
> maybe also import from json file?
> 
> like there are some json files that have periodic system of elements and such

In what way?

Unless there exists a universal standard, other sites would each differ in their json schema - I’m assuming you’re referring to exported sets in a json file?

**Comment by hwgilbert16** [comment]
This feature will include the addition of a rich text editor for cards and image support for them too.

**Comment by hwgilbert16** [comment]
Header modals will be split into separate components.
