### ISSUE TITLE
All data form set LOST!

### ISSUE THREAD

**Issue by sweetfluid** [hwgilbert16/scholarsome#130]
WTF?

I had almost 50 flashcards and then, suddenly, without any warning they are lost ( previously saved, many times). Now set have 0 flashcards. Such a waste of time.

This app is unreliable. :(

**Comment by hwgilbert16** [comment]
Are you running a local install or using the public version? If local, what commands did you use to start/update the application?

**Comment by sweetfluid** [comment]
Hi. I was using online version. No updates. Just using it casually. My
login is ***@***.***

The set was called EPONIMY I KLASYFIKACJE.






W dniu sob., 16.03.2024 o 23:33 zerxal ***@***.***>
napisał(a):

**Comment by hwgilbert16** [comment]
Sorry about that issue. I found the error and it's been fixed now on the live site.

If you email me your account's email address to `support@scholarsome.com`, I can restore your sets from a backup that was taken 1 day ago.

**Comment by hwgilbert16** [comment]
Data has been restored.

**Comment by sweetfluid** [comment]
Thank you so much.

W dniu pon., 18.03.2024 o 19:44 zerxal ***@***.***>
napisał(a):

**Comment by netchron-personal** [comment]
WHat was the issue? Facing the very same issue on my self-hosted Docker one :(

**Comment by mhays118** [comment]
I also had this happen on my self hosted version
