### ISSUE TITLE
Added new cards to existing one deletes all the card in the set

### ISSUE THREAD

**Issue by kevinlim186** [hwgilbert16/scholarsome#131]
I tried adding a new card in a set and it deleted the entire set. Good thing I have a backup. I think when you insert a new card, it does not properly fill the id, which is the primary key. This is not consistent with the old version. I hope you revert this back first to the old version, otherwise other people might also delete their entire set, which may be very difficult to recover.

**Comment by hwgilbert16** [comment]
Thanks for the heads up - this has been fixed now in the live version of the site.

If you had any sets that were affected - email me your account's email address to `support@scholarsome.com` and I can restore the sets for you.

**Comment by kevinlim186** [comment]
Thank you very much! Wishing you all the best!
