### ISSUE TITLE
Broken "Export to Quizlet" Link

### ISSUE THREAD

**Issue by BrianENguyen** [hwgilbert16/scholarsome#139]
The link on the "here" text uses "http://localhost:4200/handbook/usage/exporting-sets/#exporting-to-quizlet" rather than what I'm assuming should be [https://scholarsome.com/handbook/usage/sets/exporting-sets/](https://scholarsome.com/handbook/usage/sets/exporting-sets/)

![image](https://github.com/hwgilbert16/scholarsome/assets/33035218/04aef3f4-54c2-4d53-be08-26c181c22df8)

**Comment by hwgilbert16** [comment]
Will be fixed in the next minor release.

**Comment by hwgilbert16** [comment]
Fixed in cbcd5c6116288b3ef22c5f869725fd51e1b02abc, will be available in next minor release
