### ISSUE TITLE
remove members

### ISSUE THREAD

**Issue by diomed** [hwgilbert16/scholarsome#16]
needs close account

needs also close account after [n] days of inactivity 
n = 365 

+ same but within 30 days if nothing was made through it

honestly. i just registered with 10 min email to take a look [maybe disable that]

you should have a demo login for people who just wanna check it out. without registration

**Comment by hwgilbert16** [comment]
> needs close account
> 
> needs also close account after [n] days of inactivity n = 365
> 
> * same but within 30 days if nothing was made through it
> 
> honestly. i just registered with 10 min email to take a look [maybe disable that]
> 
> you should have a demo login for people who just wanna check it out. without registration

Additional pictures and videos will be added to the readme in the future to give people a better sense of what's available, but there won't be any expiry times for users.
