### ISSUE TITLE
Rebooting Docker host results in Scholarsome to show weird issues (maxRetriesPerRequest)

### ISSUE THREAD

**Issue by netchron-personal** [hwgilbert16/scholarsome#170]
[Scholarsome] Info      11/3/2024, 7:31:28 PM Scholarsome has started! +0ms
[Scholarsome] Error     11/3/2024, 7:39:54 PM uncaughtException: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:182:37)
    at Object.onceWrapper (node:events:633:26)
    at Socket.emit (node:events:518:28)
    at TCP.<anonymous> (node:net:337:12) - {
  error: {},
  stack: 'MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.\n' +
    '    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/event_handler.js:182:37)\n' +
    '    at Object.onceWrapper (node:events:633:26)\n' +
    '    at Socket.emit (node:events:518:28)\n' +
    '    at TCP.<anonymous> (node:net:337:12)',
  exception: true,
  date: 'Sun Nov 03 2024 19:39:54 GMT+0000 (Coordinated Universal Time)',
  process: {
    pid: 18,
    uid: 0,
    gid: 0,
    cwd: '/usr/src/app',
    execPath: '/usr/local/bin/node',
    version: 'v20.11.1',
    argv: [ '/usr/local/bin/node', '/usr/src/app/dist/apps/api/main.js' ],
    memoryUsage: {
      rss: 129478656,
      heapTotal: 52887552,
      heapUsed: 50524256,
      external: 2662880,
      arrayBuffers: 174689
    }
  },
  os: { loadavg: [ 0.01, 0.06, 0.07 ], uptime: 185775.03 },
  trace: [
    {
      column: 37,
      file: '/usr/src/app/node_modules/ioredis/built/redis/event_handler.js',
      function: null,
      line: 182,
      method: null,
      native: false
    },
    {
      column: 26,
      file: 'node:events',
      function: 'Object.onceWrapper',
      line: 633,
      method: 'onceWrapper',
      native: false
    },
    {
      column: 28,
      file: 'node:events',
      function: 'Socket.emit',
      line: 518,
      method: 'emit',
      native: false
    },
    {
      column: 12,
      file: 'node:net',
      function: null,
      line: 337,
      method: null,
      native: false
    }
  ]
} +8m

It ran fine for about 14 days and now all the flashcards are gone and this error pops up in the logs - how can I solve this?

**Comment by netchron-personal** [comment]
All Flashcards are gone :(

**Comment by hwgilbert16** [comment]
I pushed a new container image that should hopefully fix this issue.

Replace the word "latest" in line 31 of your Dockerfile with "v1.2.1". Then follow the normal update instructions (you can find them here: https://github.com/hwgilbert16/scholarsome/releases/tag/v1.2.0). Let me know if you still get the same error.

**Comment by netchron-personal** [comment]
I tried it - now redis and scholarsome are both not starting at all :(

**Comment by netchron-personal** [comment]
Fixed it by including the env-file in the compose-up command (missing in the upgrade docs)

**Comment by hwgilbert16** [comment]
I'll consider this issue resolved, will add that note to the upgrade docs
