### ISSUE TITLE
Sign up process still quite primitive

### ISSUE THREAD

**Issue by gotofritz** [hwgilbert16/scholarsome#31]
So I signed up, I never received the email (or it's been queued somewhere), there is no "send confirmation email again" button, if I click "sign up" again it tells me the email / username is already taken, but I can't login so it's a catch 22 situation

**Comment by hwgilbert16** [comment]
Know it’s what everybody says, but have you checked spam?

We’ve had issues in the past with our email provider blocking us for sending to many emails, but that should be fixed now. If not, I can reset your account for you.

I'll open an issue for this, #32

**Comment by hwgilbert16** [comment]
Fixed in #32
