### ISSUE TITLE
Title editing?

### ISSUE THREAD

**Issue by RannyBergamotte** [hwgilbert16/scholarsome#73]
I don't know if there is a way to edit the titles on existing sets, but that would be nice!

**Comment by hwgilbert16** [comment]
It's something that isn't implemented currently, but nothing is preventing us from adding it. I'll add this to the docket for the next release.

**Comment by hwgilbert16** [comment]
Fixed in 5cd584461b950183502fb4c97b5cf0ebb1a02655, will be released in next version
