### ISSUE TITLE
Basic import and export features

### ISSUE THREAD

**Issue by tymoteuszv** [hwgilbert16/scholarsome#78]
Adding a basic export feature would improve interoperability with other apps, serve as simple backup feature and much more.

Similarly, having an import feature that accepts CSV or plain text formats with simple rules would make it easier for people to move their data into the platform. This change would also allow for faster creation of flashcards through typing them line by line instead of relying on clicking various buttons within the user interface.

**Comment by hwgilbert16** [comment]
Great suggestion. This is already in the works, and it should be out in the next release. We'll have support for direct exports to Anki (as a .apkg) and Quizlet, along with a general .csv export.

https://github.com/hwgilbert16/scholarsome/issues/69

**Comment by tymoteuszv** [comment]
Great to hear, how about import though, is general (e.g. csv) importing support in the works as well?
