### ISSUE TITLE
Request: Latex or other Math Support

### ISSUE THREAD

**Issue by captain-joni** [hwgilbert16/scholarsome#79]
I love this App, but the creation of new Cards is fairly limited. 
Doing usefull physics cards is nearly impossible without a real Math implementation.
How hard would this be?

Regards

**Comment by hwgilbert16** [comment]
This was something that was planned for the future, but I'll add this to the docket now if there is community support for this feature.

**Comment by hwgilbert16** [comment]
Added in 2b4894c036bcfcfef1dce3df29f53c10637b8b66

Will be released in next update @captain-joni
