### ISSUE TITLE
Support diacritic letters with CSV import

### ISSUE THREAD

**Issue by astevens20** [hwgilbert16/scholarsome#99]
When importing a CSV file that includes diacritic letters (such as ä), they display as the � replacement character instead. As a workaround, I am able to manually type diacritic letters into flashcards.

CSV file:
![Finnish Nouns CSV](https://github.com/hwgilbert16/scholarsome/assets/158517674/d2659010-b016-413e-b185-f3aeffc29921)

After import:
![Finnish Nouns After Import](https://github.com/hwgilbert16/scholarsome/assets/158517674/677e25e2-f5a6-4571-a243-fba8132bdf21)

**Comment by hwgilbert16** [comment]
Non-standard unicode characters should still work - probably something with our XSS protections. This will be fixed in the next update.

**Comment by hwgilbert16** [comment]
I am unable to reproduce this error on my end. I replicated the same set that you were importing, and it imported via CSV with no character issues.

Have you tried importing on a separate device? It's possible that the one you tried this on formatted the file in a non-standard way.

<img width="1279" alt="image" src="https://github.com/hwgilbert16/scholarsome/assets/44120703/d47a5562-b252-47f1-99e9-7409bdabcb7c">

**Comment by astevens20** [comment]
I'm trying on a different computer now; it seems to be dependent on exactly how I create the .csv file.

_A few relevant test cases:_
1. When I create a document in Excel and save as a .csv file using the "CSV (Comma delimited) (*.csv)" option, I **do** experience the issue.
![image](https://github.com/hwgilbert16/scholarsome/assets/158517674/9006998f-e5df-427a-b8bc-9e76f4023a2f)

2. If I manually type the words into notepad and save as a .txt file, I **do not** experience the issue.

3. If I create a document in Excel and save as a .csv file using the "CSV UTF-8 (Comma delimited) (*.csv)" option, I **do not** experience the issue.

4. If I create a document in Excel and save as a .csv file using the "CSV (MS-DOS) (*.csv)" option, I **do** experience the issue.


_Probably irrelevant things I tried_

5. If I create a document in Excel and save as a .csv file, then manually change the file extension to .txt in file explorer, then upload the file, I **do** experience the issue.

6. If I manually type the words into notepad and save as a .txt file, then manually change the file extension to .csv in file explorer, then upload the file, I **do not** experience the issue

**Comment by hwgilbert16** [comment]
This issue more lays with how Excel encodes CSV files in different ways depending on output settings. If the CSV UTF-8 option works, then just stick with that.

I'll add a warning to the documentation page to use CSV UTF-8 if creating sets within Excel.

**Comment by hwgilbert16** [comment]
Fixed in dea2f00ba946ae2fb34c4ded72bac504b830e148
